### ISSUE TITLE
Regarding downloading this package

### ISSUE THREAD

**Issue by timberleys** [garethhallnz/pandadoc#2]
I am unable to download this package.And getting this message-The requested package garethhallnz/pandadoc * is satisfiable by garethhallnz/pandadoc[dev-master, dev-pandadoc-guzzle-v6] but these conflict with your requirements or minimum-stability

**Comment by garethhallnz** [comment]
Issue fixed [Set guzzle version](https://github.com/garethhallnz/pandadoc/commit/04fe3d9b4bc4362da63492e460cd20a002001e72)

Will look at updating code to support version 6 soon

**Comment by timberleys** [comment]
I want to create document using pdf But I am unable to do that because you don't have method regarding this.
