### ISSUE TITLE
wrong field name & additional fields

### ISSUE THREAD

**Issue by flynfish** [garethhallnz/pandadoc#3]
Based on [pandadoc api](https://developers.pandadoc.com/v1/reference#create-document-from-pandadoc-template), for the document builder you have a field  called `meta`, but it should be `metadata`.

I also noticed that the document builder is missing `pricing_tables` field. 

Any chance you could add those quickly or do you want a PR submitted?

**Comment by garethhallnz** [comment]
Issue resolved in https://github.com/garethhallnz/pandadoc/commit/2a8e6fb58df095502abbb859089cf91588b832c5

**Comment by flynfish** [comment]
@garethhallnz what about pricing_tables support? Thanks for the other update with metadata!

**Comment by garethhallnz** [comment]
I am abit under the gun with some other projects; can you fork and do a pull request?
